server:
  port: 8081
spring:
  datasource:
     url: jdbc:postgresql://localhost:5432/Oselan
     hikari:
       maximumPoolSize: ${DATASOURCE_MAX_POOL_SIZE:1}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate: 
        default_schema: jpalookupstest
        format_sql: true
  flyway:
    enabled: true
    fail-on-missing-locations: true
    locations: classpath:db/migration
    user: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:12345678}
    url:  jdbc:postgresql://localhost:5432/Oselan
    schemas: jpalookupstest
#DISPLAY QUERY PARAMETERS
logging:
  level:
    org.hibernate.type: OFF
    org.hibernate.SQL: OFF
    org.hibernate.cache: DEBUG
    org.springframework.transaction: OFF
    org.hibernate.type.descriptor.sql: OFF 